apiVersion: v1
kind: Service
metadata:
  name: k8s-claimer
  labels:
    heritage: deis
    app: k8s-claimer
spec:
  type: LoadBalancer
  ports:
  - port: 80
    name: http
    targetPort: http
  selector:
    app: k8s-claimer
