apiVersion: v1
kind: Service
metadata:
  name: k8s-claimer
  namespace: deis
  labels:
    heritage: k8s-claimer
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    app: k8s-claimer
